# Generated by Django 3.1.5 on 2021-01-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='bal',
            field=models.FloatField(default=0),
        ),
    ]
