# Generated by Django 3.1.5 on 2021-01-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20210124_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.TextField(blank=True, null=True)),
                ('ref', models.TextField(blank=True, null=True)),
                ('amount', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'log',
            },
        ),
    ]
