# Generated by Django 3.1.5 on 2021-01-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='rmobile',
            field=models.TextField(blank=True, null=True),
        ),
    ]
