# Generated by Django 3.1.5 on 2021-01-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_log_rmobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.TextField(blank=True, null=True)),
                ('pin', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pins',
            },
        ),
    ]
