# Generated by Django 3.1.5 on 2021-01-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_pins'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='fee',
            field=models.TextField(blank=True, null=True),
        ),
    ]
