# Generated by Django 3.1.5 on 2021-01-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_log_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=255, verbose_name='mobile'),
        ),
    ]
